id: PD7BB77DD
initial_creation_type: ocr
source_metadata:
  volumes:
    101d1bb122d9489da851817013d34f11:
      base_file: v047.txt
      image_group_id: I1PD95892
      title: སྦྱིན་སྲེག་གི་ཆོ་ག།
      total_pages: 1464
      volume_number: 47
